version: '3.8'

services:
  festival-backend:
    build: ./backend
    container_name: tomorrowland-backend
    ports:
      - "5000:5000"
    volumes:
      # Modificato per mappare correttamente la cartella dove server.py scrive i log
      - ./logs:/var/log/tomorrowland_festival
    environment:
      - PYTHONUNBUFFERED=1
      - VULNERABILITY_ENABLED=${VULNERABILITY_ENABLED}
      - SECRET_KEY=${SECRET_KEY}

  wazuh-manager:
    image: wazuh/wazuh-manager:4.7.2
    container_name: tomorrowland-wazuh
    ports:
      - "56000:55000"
    volumes:
      - ./wazuh_config/local_rules.xml:/wazuh-config-mount/etc/rules/local_rules.xml:ro
      - ./wazuh_config/ossec.conf:/wazuh-config-mount/etc/ossec.conf:ro
      - ./logs:/var/log/tomorrowland_festival:ro
      - ./logs/wazuh_logs:/var/ossec/logs